export {default as Signup} from './Signup/Signup';
export {default as Login} from './Login/Login';
export {default as HomePage} from './HomePage/HomePage';
export {default as MainPage} from "./MainPage/MainPage"
export {default as Cart} from "./Cart/Cart"
export {default as LatestDeals} from "./LatestDeals/LatestDeals"
export {default as Profile} from "./Profile/Profile"
export {default as OrderDetail} from "./OrderDetail/OrderDetail"
export {default as FinalOrder} from "./FinalOrder/FinalOrder"
export {default as OrderTrack} from "./OrderTrack/OrderTrack"