export default{
    back: require('../assets/Images/back.png'),
    dp: require('../assets/Images/dp.png'),
    rightBack: require('../assets/Images/rightBack.png'),
    camera: require('../assets/Images/camera.png'),
    gallery: require('../assets/Images/gallery.png'),



    logoMyntra :require('../assets/Images/logoMyntra.png'),
    name: require('../assets/Images/name.png'),
    password: require('../assets/Images/password.png'),
    email:require('../assets/Images/email.png'),
    phone:require('../assets/Images/phone.png'),
    menu:require('../assets/Images/menu.png'),
    bell:require('../assets/Images/bell.png'),
    search:require('../assets/Images/search.png'),
    cart:require('../assets/Images/cart.png'),
    heart:require('../assets/Images/heart.png'),
    modalTop: require('../assets/Images/modalImg.jpg'),
    casualShoes: require('../assets/Images/Casual-Shoe.jpg'),
    sportsShoes: require('../assets/Images/Sports-Shoe.jpg'),
    jeans: require('../assets/Images/Jeans.jpg'),
    tshirt: require('../assets/Images/T-shirt.png'),
    flipFlop: require('../assets/Images/Flipflop.jpg'),
    sale:require('../assets/Images/sale.jpg'),
    sc:require('../assets/Images/sc.jpg'),
    kotak:require('../assets/Images/kotak.jpg'),
    bob:require('../assets/Images/bob.jpg'),
    flat: require('../assets/Images/flat.jpg'),
    crazy: require('../assets/Images/crazyDeals.jpg'),
    crazy1: require('../assets/Images/crazy1.jpg'),
    crazy2: require('../assets/Images/crazy2.jpg'),
    crazy3: require('../assets/Images/crazy3.jpg'),
    budget: require('../assets/Images/budget.jpg'),
    budget2: require('../assets/Images/budget2.jpg'),
    footware: require('../assets/Images/footware.jpg'),

    shoe1: require('../assets/Images/shoe1.jpg'),
    shoe2: require('../assets/Images/shoe2.jpg'),
    shoe3: require('../assets/Images/shoe3.jpg'),  
    shoe4: require('../assets/Images/shoe4.jpg'),  
    shoe5: require('../assets/Images/shoe5.jpg'),  
    shoe6: require('../assets/Images/shoe6.jpg'),  
    shoe7: require('../assets/Images/shoe7.jpg'),  
    shoe8: require('../assets/Images/shoe8.jpg'),  


    logo: require('../assets/Images/logo.png'),
    google: require('../assets/Images/google.png'),
    facebook: require('../assets/Images/facebook.png'),
bag: require('../assets/Images/bag.png'),
offer: require('../assets/Images/offer.png'),
men: require('../assets/Images/men.jpg'),
women: require('../assets/Images/women.jpg'),
kids: require('../assets/Images/kids.jpg'),
beauty: require('../assets/Images/beauty.jpg'),
footwear: require('../assets/Images/footwear.jpg'),
home: require('../assets/Images/home.jpg'),
jewllery: require('../assets/Images/jwellery.jpg'),
gadgets: require('../assets/Images/gadgets.jpg'),
ss21: require('../assets/Images/ss21.jpg'),
dress: require('../assets/Images/dress.png'),
handbag: require('../assets/Images/handbag.png'),
heels: require('../assets/Images/heels.png'),
trackpant: require('../assets/Images/trackpant.png'),
explore: require('../assets/Images/explore.jpg'),
myntraMall: require('../assets/Images/myntramall.png'),
king: require('../assets/Images/king.png'),
gift: require('../assets/Images/gift.png'),
earn: require('../assets/Images/earn.png'),
move: require('../assets/Images/move.png'),
refer: require('../assets/Images/refer.png'),
scan: require('../assets/Images/scan.png'),
star: require('../assets/Images/star.png'),
myntraClass: require('../assets/Images/myntraClass.png'),
back: require('../assets/Images/back.png'),
share: require('../assets/Images/share.png'),
eye: require('../assets/Images/eye.png'),
cart1: require('../assets/Images/cart1.jpg'),
camera: require('../assets/Images/camera.png'),
gallery: require('../assets/Images/gallery.png'),
background: require('../assets/Images/background.png'),
dp: require('../assets/Images/dp.png'),
pencil: require('../assets/Images/pencil.png'),
order: require('../assets/Images/order.png'),
help: require('../assets/Images/help.png'),
dial: require('../assets/Images/dial.png'),
email: require('../assets/Images/emaill.png'),
map: require('../assets/Images/googleMap.jpg'),
bag1: require('../assets/Images/bag1.png'),
share1: require('../assets/Images/share1.png'),
tik: require('../assets/Images/tik.png'),
dot: require('../assets/Images/dot.png')
}
